version: "3.9"
services:
  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_data:/etc/nginx
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
volumes:
  nginx_data:
