version: "3.9"
services:
  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_data:/etc/nginx
    networks:
      - nginx_network
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
volumes:
  nginx_data:
    external: true
networks:
  nginx_network:
    external: true
    
# External true quiere decir que el volumen o el network ha sido creado fuera del docker-compose, por lo tanto el docker-compose va a fallar si no ha sido creado.
# docker volume create nginx_data
# docker network create nginx_network
